// react-demo/src/components/ListItem/index.js
import React from "react"
import "./index.css"

const ListItem = ({ result: { name, description, thumbnail}}) => {
  const { path, extension } = thumbnail
  const srcImage = `${path}.${extension}`
  return (
    <li className="ListItem">
      <div className="card">
        <img
          className="card-img-top"
          src={srcImage}
          alt=""
        />
        <div className="card-body">
          <h5 className="card-title">{name}</h5>
          <p className="card-text">{description}</p>
        </div>
      </div>
    </li>
  )
}
  

export default ListItem

// angular-demo/src/app/list-item/list-item.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'app-list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.css']
})
export class ListItemComponent implements OnInit {
  @Input() data: any = {}
  srcImage: string = ''
  ngOnInit() {
    const { path, extension } = this.data.thumbnail
    this.srcImage = `${path}.${extension}`
  }

}

<div class="ListItem">
  <div class="card">
    <img
      class="card-img-top"
      [src]="srcImage"
      alt=""
    />
    <div class="card-body">
      <h5 class="card-title">{{ data.name }}</h5>
      <p class="card-text">{{ data.description }}</p>
    </div>
  </div>
</div>
