// vue-demo/src/components/Search.vue
<template>
  <form class="Search form-inline" @submit.prevent="handleSubmit">
    <label class="sr-only">Name</label>
    <input 
      type="text" 
      class="Search-input form-control mb-2 mr-sm-2" 
      placeholder="Ex: Captain America" 
      v-model="query"
    />
    <button type="submit" class="btn btn-primary mb-2">Submit</button>
  </form>    
</template>

<script>
  // https://alligator.io/vuejs/vue-form-handling/

  export default {
    data() {
      const query = ''
      return { query }
    },
    methods: {
      handleSubmit() {
        this.$emit('do-search', this.query)
      }
    }
  }
</script>

// react-demo/src/components/Search/index.js
import React, { Component } from 'react';

class Search extends Component {
  constructor(props) {
    super(props)
    this.state = {
      query: ''
    }
  }

  handleChange = e => {
    const query = e.target.value
    this.setState({ query })
  }

  handleSubmit = e => {
    e.preventDefault()
    const {query} = this.state
    this.props.search(query)
  }

  render() {
    return (
      <form className="Search form-inline" onSubmit={ this.handleSubmit }>
        <label className="sr-only">Name</label>
        <input 
          type="text" 
          className="Search-input form-control mb-2 mr-sm-2" 
          placeholder="Ex: Captain America" 
          value={ this.state.value }
          onChange={ this.handleChange }
        />
        <button type="submit" className="btn btn-primary mb-2">Submit</button>
      </form>    
    )
  }
}

export default Search;
