// vue-demo/src/components/Search.vue
<template>
  <form class="Search form-inline" @submit.prevent="handleSubmit">
    <label class="sr-only">Name</label>
    <input 
      type="text" 
      class="Search-input form-control mb-2 mr-sm-2" 
      placeholder="Ex: Captain America" 
      v-model="query"
    />
    <button type="submit" class="btn btn-primary mb-2">Submit</button>
  </form>    
</template>

<script>
  // https://alligator.io/vuejs/vue-form-handling/

  export default {
    data() {
      const query = ''
      return { query }
    },
    methods: {
      handleSubmit() {
        this.$emit('do-search', this.query)
      }
    }
  }
</script>

// angular-demo/src/app/search/search.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html'
})
export class SearchComponent  {
  query = ''
  @Input() message;
  @Output() search = new EventEmitter();

  submitSearch(event) {
    event.preventDefault()
    this.search.emit(this.query);
  }

}

<form class="Search form-inline" (submit)="submitSearch($event)">
  <label class="sr-only">Name</label>
  <input
    type="text"
    class="Search-input form-control mb-2 mr-sm-2"
    placeholder="Ex: Captain America"
    [(ngModel)]="query"
    name="query field"
  />
  <button type="submit" class="btn btn-primary mb-2">Submit</button>
</form>
