// react-demo/src/components/App/index.js
import React, { Component } from 'react';
import { Search, ListResults } from 'components';
import * as serviceApi from 'services/serviceApiMarvel'

class App extends Component {
  constructor() {
    super()
    this.state = {
      results : []
    }
  }

  searchSuperHero = query => {
    serviceApi.searchSuperHero(query)
      .then( results => this.setState({ results })) 
  }

  render() {
    const { results } = this.state
    return (
      <div className="App">
        <div className="container">
          <h1>SuperHero Finder</h1>
          <Search search={ this.searchSuperHero } />
          <ListResults results={ results } />
        </div>
      </div>
    )
  }
}

export default App;

// vue-demo/src/components/App.vue
<template>
  <div class="App">
    <div class="container">
      <h1>SuperHero Finder</h1>
      <Search v-on:do-search="searchSuperHero($event)"/>
      <ListResults v-bind:results="results"/>
    </div>
  </div>
</template>

<script>
import * as serviceApi from '@/services/serviceApiMarvel'
import { Search, ListResults } from '@/components'

export default {
  data() {
    const results = []
    return { results }
  },
  components: {
    Search, 
    ListResults
  },
  methods: {
    searchSuperHero: function(query) {
      serviceApi.searchSuperHero(query)
        .then( results => {
          this.results = results
        }) 
    }
  }
}
</script>
