// angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { ApiMarvelService } from './api-marvel.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent {
  results = [];
  constructor(
    public apiMarvelService: ApiMarvelService
  ) {}

  getHeroes(query) {
    this.apiMarvelService.searchHeroes(query)
      .subscribe(({ data: { results } }) => this.results = results);
  }
}


<div class="App">
  <div class="container">
    <h1>SuperHero Finder</h1>
    <app-search (search)="getHeroes($event)"></app-search>
    <app-list-results [results]="results"></app-list-results>
  </div>
</div>

// vue-demo/src/components/App.vue
<template>
  <div class="App">
    <div class="container">
      <h1>SuperHero Finder</h1>
      <Search v-on:do-search="searchSuperHero($event)"/>
      <ListResults v-bind:results="results"/>
    </div>
  </div>
</template>

<script>
import * as serviceApi from '@/services/serviceApiMarvel'
import { Search, ListResults } from '@/components'

export default {
  data() {
    const results = []
    return { results }
  },
  components: {
    Search, 
    ListResults
  },
  methods: {
    searchSuperHero: function(query) {
      serviceApi.searchSuperHero(query)
        .then( results => {
          this.results = results
        }) 
    }
  }
}
</script>
